version: '3'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  app:
    image: test-steamlinks
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: postgresql://postgres:root@database:5432/app?serverVersion=13&charset=utf8
    volumes:
      - .:/var/www
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8082:80"
    depends_on:
      - database
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test

volumes:
  ###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###