version: '3.9'
services:
  web:
    build: Docker/nginx/.
    ports:
      - "8080:80"
    networks:
      - app
    volumes:
      - .:/var/www:cached
      - /var/www/vendor
      - /var/www/var

  php:
    env_file: docker.env
    environment:
      - KEY_STEAM=$${KEY_STEAM}
    build:
      context: .
      dockerfile: ./Docker/Dockerfile
    tty: true
    expose:
      -   9000
    volumes:
      - .:/var/www:cached
      - /var/www/vendor
      - /var/www/var
    networks:
      - app
      - bdd

  db:
    image: postgres:14
    restart: always
    ports:
      -   "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    networks:
      - app
      - bdd
    volumes:
      - db:/var/lib/postgressql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234
    ports:
      - '5050:5050'
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    networks:
      - app


volumes:
  db:
  var:
  vendor:
  pgadmin:
networks:
  app:
  bdd:
    external:
      name: external-bdd